"""Server-owned text; never generated by the model."""

from typing import Literal

ActionType = Literal["ACT_LOGIN", "ACT_PAYMENT", "ACT_APP", "ACT_LINK", "ACT_PERSONAL", "PRESSURE"]
UserAction = Literal[
    "NOT_INTERACTED",
    "OPENED_LINK",
    "SUBMITTED_CREDENTIALS",
    "SUBMITTED_PERSONAL",
    "SENT_MONEY",
    "INSTALLED_APP",
    "UNKNOWN",
]
FallbackReason = Literal[
    "AI_TIMEOUT", "AI_UNAVAILABLE", "AI_BLOCKED", "AI_OUTPUT_INVALID", "EVIDENCE_INVALID"
]
SensitiveType = Literal["PASSWORD", "OTP", "PHONE", "EMAIL", "ACCOUNT", "RRN", "CARD"]
ACTION_LABELS = {
    "ACT_LOGIN": "로그인 요구",
    "ACT_PAYMENT": "송금·결제 요구",
    "ACT_APP": "앱 설치 요구",
    "ACT_LINK": "링크 접속 요구",
    "ACT_PERSONAL": "개인정보·금융정보 입력 요구",
    "PRESSURE": "긴급성·불이익 강조",
}
ACTION_ORDER = list(ACTION_LABELS)
USER_ACTION_ORDER = [
    "NOT_INTERACTED",
    "OPENED_LINK",
    "SUBMITTED_CREDENTIALS",
    "SUBMITTED_PERSONAL",
    "SENT_MONEY",
    "INSTALLED_APP",
    "UNKNOWN",
]
PII_ORDER = ["PASSWORD", "OTP", "PHONE", "EMAIL", "ACCOUNT", "RRN", "CARD"]
LIMITATION = "이 결과만으로 피싱 또는 실제 침해 여부를 확정할 수 없습니다."
VERIFIED_NOTICE = "원문에서 확인된 행동 요구입니다. 인용 일치는 의미 해석의 정확성을 보장하지 않습니다."
NO_ACTION_NOTICE = "추출된 행동 요구가 없습니다. 이 결과가 메시지의 안전성을 의미하지는 않습니다."
FALLBACK_NOTICE = "자동 분석 결과를 원문 근거로 검증하지 못했거나 분석을 완료하지 못했습니다. 메시지 속 링크를 누르거나 정보를 입력하지 말고, 주장하는 서비스의 공식 앱 또는 직접 입력한 주소에서 확인하세요."
GUIDANCE_NOTICE = "선택한 행동에 따른 일반 대응 안내입니다. 실제 피해 여부를 의미하지 않습니다."
PROMPT_VERSION = "1.0"
MAX_REQUEST_BYTES = 32768
MAX_MESSAGE_CODEPOINTS = 5000
MAX_AI_OUTPUT_BYTES = 32768
MAX_EVIDENCE_ITEMS = 12
MAX_QUOTE_CODEPOINTS = 500
MAX_SPANS_PER_QUOTE = 20
ERROR_MESSAGES = {
    "INVALID_JSON": "올바른 UTF-8 JSON 요청을 보내 주세요.",
    "INVALID_REQUEST": "요청 필드와 값의 형식을 확인해 주세요.",
    "CONSENT_REQUIRED": "외부 AI 전송 동의가 필요합니다.",
    "INPUT_POLICY_VIOLATION": "공백뿐인 본문 또는 허용되지 않는 문자가 있습니다.",
    "SENSITIVE_DATA_DETECTED": "민감정보로 의심되는 값이 있습니다. 값을 삭제한 뒤 다시 시도해 주세요.",
    "PAYLOAD_TOO_LARGE": "요청 크기는 32 KiB 이하여야 합니다.",
    "UNSUPPORTED_MEDIA_TYPE": "압축하지 않은 UTF-8 application/json 요청을 보내 주세요.",
    "RATE_LIMITED": "요청이 많습니다. 잠시 후 직접 다시 시도해 주세요.",
    "SERVICE_BUSY": "현재 분석 요청이 많습니다. 잠시 후 직접 다시 시도해 주세요.",
    "INTERNAL_ERROR": "요청 처리 중 오류가 발생했습니다.",
    "NOT_FOUND": "요청한 경로가 없습니다.",
    "METHOD_NOT_ALLOWED": "허용되지 않는 요청 메서드입니다.",
}
ERROR_STATUS = {
    "INVALID_JSON": 400,
    "INVALID_REQUEST": 422,
    "CONSENT_REQUIRED": 400,
    "INPUT_POLICY_VIOLATION": 400,
    "SENSITIVE_DATA_DETECTED": 400,
    "PAYLOAD_TOO_LARGE": 413,
    "UNSUPPORTED_MEDIA_TYPE": 415,
    "RATE_LIMITED": 429,
    "SERVICE_BUSY": 503,
    "INTERNAL_ERROR": 500,
    "NOT_FOUND": 404,
    "METHOD_NOT_ALLOWED": 405,
}
